### ISSUE TITLE
 the iv_system pre-trained model's link  seems to have failed  

### ISSUE THREAD

**Issue by zhangshenyu7105** [SEC4SR/SEC4SR#1]

**Comment by zhangshenyu7105** [comment]
the iv_system pre-trained model's link seems to have failed

**Comment by SEC4SR** [comment]
Thanks for your feedback, but the link seems to works fine. Did you turn on the proxy? Or maybe you need to try multiple times due to the unstable internet connection with Google driver and the large size of iv_system (more than 300M). We tried three times and finally made it. 🤣 

Due to anonymous problem, currently we can only provide google driver link to download these files. After our manuscript is available online, we will put these files in a more stable website. Thanks for your understanding.

BTW, we are still working hard to improve the comprehensibility and readability of our code. It is still an active project. Welcome to stay tuned! :smile:

**Comment by zhangshenyu7105** [comment]
Thanks for your answer,I will try a few more times
