### ISSUE TITLE
KeyError: 'fc.bias'

### ISSUE THREAD

**Issue by muzihuole** [SEC4SR/SEC4SR#6]
Dear author,
When I use the pretrained natural_audio model to generate adversarial examples, I run the code as that :
`python attackMain.py -task CSI -root ./data -name Spk251_test -des ./adver-audio/audionet-fakebob audionet_csine -extractor ./model_file/natural-audionet FAKEBOB -epsilon 0.002`.
However, I find an error as follow:
```
Traceback (most recent call last):
File "attackMain.py", line 320, in
main(parse_args())
File "attackMain.py", line 164, in main
base_model = audionet_csine(args.extractor, label_encoder=args.label_encoder, device=device)
File "C:\Lis\SEC4SR\model\audionet_csine.py", line 33, in init
num_class = model_state_dict['fc.bias'].shape[0]
KeyError: 'fc.bias'
```
Hope to get your help! Thank you.

**Comment by SEC4SR** [comment]
Could you please print the variable `model_state_dict` and provide me the log? Just like this.
<img width="422" alt="image" src="https://user-images.githubusercontent.com/85487197/146676117-ccf75b2b-17a3-41f2-bd90-c6fe1010a677.png">

**Comment by SEC4SR** [comment]
Oh, sorry. I think I know what the problem is.

**Comment by SEC4SR** [comment]
Last week, I made a major change to the repo by separating the models and defenses (previously they were mixed), during which maybe I introduced some new bug. I will thoroughly test the code.

Temporal solution for your issue:
```
defended_model_ckpt = ./model_file/natural-audionet
defened_model_state_dict = torch.load(defended_model_ckpt, map_location='cpu')
model_state_dict = defened_model_state_dict['base_model'].state_dict()
model_ckpt = './model_file/natural-audionet-2
torch.save(model_state_dict, model_ckpt)
```

And then input `./model_file/natural-audionet-2` to `attackMain.py`

The root of this issue is that `./model_file/natural-audionet` is the state_dict of `defended_model`, not `audionet_csine`, so there is no a key named `fc.bias`

**Comment by muzihuole** [comment]
Thanks for your reply, and the problem is like that:
![778264bc490d2085bb8b77dcaa43bb1](https://user-images.githubusercontent.com/71002687/146676699-36a693d7-85a3-4478-90c2-8f9291c1c222.png)
Obviously the model has a `base_model` prefix.
I will try your method.

**Comment by SEC4SR** [comment]
I have changed the `torch.save(model.state_dict(), model_ckpt)` to `torch.save(model.base_model.state_dict(), model_ckpt)` in `natural_train.py` and `adver_train.py`. Make a pull please.

If you don't want to train the model again, you can adopt the solution I mentioned before (probably not work since there is no `base_model` key in your picture), or simply change the the Line 33 of `model/audionet_csine.py` to `num_class = model_state_dict['base_model.fc.bias'].shape[0]`

**Comment by SEC4SR** [comment]
Oh, the second solution may also not work.

If you don't want to train the model again, try this please:
```
defended_model_ckpt = ./model_file/natural-audionet
defened_model_state_dict = torch.load(defended_model_ckpt, map_location='cpu')
model_state_dict = dict()
for k, v in defened_model_state_dict.items():
     if 'base_model' in k:
         k_2 = k[11:] # remove base_model prefix
         model_state_dict[k_2] = v
model_ckpt = './model_file/natural-audionet-2
torch.save(model_state_dict, model_ckpt)
model_state_dict = defened_model_state_dict['base_model'].state_dict()
model_ckpt = './model_file/natural-audionet-2
torch.save(model_state_dict, model_ckpt)
```
Input ./model_file/natural-audionet-2 to attackMain.py:
```
python attackMain.py -task CSI -root ./data -name Spk251_test \
-des ./adver-audio/audionet-fakebob audionet_csine \
-extractor ./model_file/natural-audionet-2 \
FAKEBOB -epsilon 0.002
```

**Comment by muzihuole** [comment]
Copy that. Thank you very much.

**Comment by muzihuole** [comment]
I have retrained the model and successfully generated adversarial examples with the model. 
I will close this issue. Thanks for your code.
